export const MESSAGES = {
  delete: "Deleted!",
  taskCreated: "Task Created",
  taskUpdated: "Task Updated",
  taskDeleted: "Task Deleted",
  taskEdited: "Task Edited",
  blogCreated: "Blog Created",
  blogUpdated: "Blog Updated",
  blogDeleted: "Blog Deleted",
  blogEdited: "Blog Edited",
  invalidId: "Invalid Id",
  noContent: "There is no data!",
  badRequest: "Bad Request!",
  noMatchPassword: "Current Password is in-correct!",
  updateProfile: "Profile Updated",
  updateRole: "User Role Updated!",
  deleteAdmin: "User Deleted!",
  adminHasContent: "Admin has content!",
  
  confirmPassword: "رمز عبور جدید نادرست است!",
  existItemCategory: "شما قبلاً این آیتم را انتخاب کرده‌اید",
  addItemCategory: "آیتم اضافه شد",
  brandField: "لطفا نام و تصویر برند را وارد کنید.",
  addBrand: "برند با موفقیت اضافه شد.",
  deleteImage:"تصویر با موفقیت حذف شد!",
  highSizeImage:"حجم تصویر بیش از حد مجاز است!",
  putImage: "تصویر مورد نظر را قرار بدید!",
  imageNotFound: "تصویر موجود نیست!",
  addBrandImageErr: "خطا در آپلود لوگو. لطفا دوباره تلاش کنید.",
  nameRequired: "فیلد نام را پر کنید",
  slugRequired: "فیلد اسلاگ را پر کنید",
  slugAlreadyExists: "اسلاگ از قبل وجو دارد",
  categoryCreated: "دسته‌بندی ایجاد شد",
  productEdited: "محصول ویرایش شد",
  productCreated: "محصول ایجاد شد",
  productDeleted: "محصول حذف شد",
  categoryEdited: "دسته‌بندی ویرایش شد",
  categoryDeleted: "دسته‌بندی حذف شد",
  categoryNotFound: "دسته‌بندی پیدا نشد",
  productNotFound: "محصول پیدا نشد",
  fields: "تمام فیلدها را پر کنید!",
  unAuthorized: "شما مجاز نیستید!",
  categoryAlreadyExists: "دسته‌بندی از قبل وجود دارد!",
  forbidden: "دسترسی ممنوع!",
  addKeywords: "کلید واژه اضافه شد",
  addSubcategories: "زیردسته‌بندی اضافه شد",
  editSubcategories: "زیردسته‌بندی ویرایش شد",
  sameKey: "شما قبلاً این کلمه کلیدی را انتخاب کرده اید",
  userNotFound: "نام کاربری یا رمز عبور صحیح نیست!",
  aUserNotFound: "کاربر پیدا نشد!",
  userShouldNotEmpty: "نام کاربری نباید خالی باشد!",
  register: "ثبت نام با موفقیت انجام شد",
  login: "با موفقیت وارد شدید!",
  user_exist: "نام کاربری از قبل وجود دارد!",
  fillInp: "لطفا داده های معتبر را وارد کنید!",
  success: "موفق",
  update: "آپدیت شد!",
  failed: "شکست خورد",
  server: "خطا در ارتباط با سرور",
};

export const STATUS_CODES = {
  success: 200,
  created: 201,
  updated: 202,
  badRequest: 400,
  unAuthorized: 401,
  forbidden: 403,
  exist: 422,
  not_found: 404,
  conflict: 409,
  server: 500,
};
