export const MESSAGES = {
  update: "Updated!",
  delete: "Deleted!",
  productCreated: "Product Created",
  categoryCreated: "Category Created",
  taskCreated: "Task Created",
  taskUpdated: "Task Updated",
  taskDeleted: "Task Deleted",
  taskEdited: "Task Edited",
  blogCreated: "Blog Created",
  blogUpdated: "Blog Updated",
  blogDeleted: "Blog Deleted",
  blogEdited: "Blog Edited",
  invalidId: "Invalid Id",
  noContent: "There is no data!",
  productEdited: "Product Edited",
  categoryEdited: "Category Edited",
  badRequest: "Bad Request!",
  noMatchPassword: "Current Password is in-correct!",
  fields: "Fill all fields!",
  image: "Please put image!",
  updateProfile: "Profile Updated",
  updateRole: "User Role Updated!",
  deleteAdmin: "User Deleted!",
  adminHasContent: "Admin has content!",

  unAuthorized: "شما مجاز نیستید!",
  categoryAlreadyExists: "دسته‌بندی از قبل وجود دارد!",
  forbidden: "دسترسی ممنوع!",
  addKeywords: "کلید واژه اضافه شد",
  sameKey: "شما قبلاً این کلمه کلیدی را انتخاب کرده اید",
  userNotFound: "نام کاربری یا رمز عبور صحیح نیست!",
  register: "ثبت نام با موفقیت انجام شد",
  login: "با موفقیت وارد شدید!",
  user_exist: "نام کاربری از قبل وجود دارد!",
  fillInp: "لطفا داده های معتبر را وارد کنید!",
  success: "موفق",
  failed: "شکست خورد",
  server: "خطا در ارتباط با سرور",
};

export const STATUS_CODES = {
  success: 200,
  created: 201,
  updated: 202,
  badRequest: 400,
  unAuthorized: 401,
  forbidden: 403,
  exist: 422,
  not_found: 404,
  conflict: 409,
  server: 500,
};
